CREATE DATABASE vehicle_security;
USE vehicle_security;

DROP TABLE IF EXISTS VEHICLES;

CREATE TABLE VEHICLES(
MANUFACTURER VARCHAR(25),
MODEL  VARCHAR(25),
LICENSE_NO VARCHAR(25) PRIMARY KEY,
SOCIETY VARCHAR(25),
PARKING_LOT_NO VARCHAR(25));

DROP TABLE IF EXISTS BASE;
CREATE TABLE BASE(
LICENSE_NO VARCHAR(25),
DETECTION_TIMESTAMP DATETIME,
CAMERA_POSITION ENUM('ENTRY', 'EXIT'));

SELECT * FROM VEHICLES;
TRUNCATE TABLE VEHICLES;

DROP TABLE IF EXISTS PERSON;
CREATE TABLE PERSON(
PERSON_NAME VARCHAR(50),
AGE INT, 
GENDER ENUM('MALE','FEMALE', 'OTHER'),
CONTACT_NO VARCHAR(13),
SOCIETY VARCHAR(25),
FLAT_NO VARCHAR(15),
AADHAR_NO VARCHAR(12) PRIMARY KEY);

DESCRIBE PERSON;

TRUNCATE TABLE PERSON;
SELECT * FROM PERSON;
